title:			kr0no.me
email:			kr0no@ka0labs.net
description: 		"Seguridad informática y otras hierbas."
timezone:		Europe/Madrid
url: 			"https://kr0no.me"
baseurl: 		""
permalink: 		/post/:year/:month/:title
keywords:		""

author_name:		kr0no
twitter_username: 	Aitor_FL
github_username:  	kr0no

# Build settings
highliter:		rouge
markdown:		kramdown
encoding:		utf-8

plugins:
  - jekyll-feed

remote_theme: kr0no/kr0no.me-theme

# Other things
collections:
    projects:
        output: 	true
        permalink:	/projects/:title